name: Weights
options:
  createIntermediateGroups: true
  indentWidth: 4
  tabWidth: 4
  groupSortPosition: top
  bundleIdPrefix: "com.lukaszkasperek"
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: 1320
packages:
  Quick:
    url: https://github.com/Quick/Quick
    from: 4.0.0
  Nimble:
    url: https://github.com/Quick/Nimble
    from: 9.2.1
targets:
  Weights:
    type: application
    platform: iOS
    settings:
      TARGETED_DEVICE_FAMILY: 1
    sources:
      - path: Weights
    dependencies:
      - target: Core
      - target: Services
  WeightsTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: WeightsTests
    dependencies:
      - target: Weights
  Core:
    type: framework
    platform: iOS
    sources:
      - path: Core
        excludes:
          - "**/*_tests.swift"
  CoreTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CoreTests
      - path: Core
        includes:
          - "**/*_tests.swift"
    dependencies:
      - target: Core
      - package: Quick
      - package: Nimble
  Services:
    type: framework
    platform: iOS
    sources:
      - path: Services
        excludes:
          - "**/*_tests.swift"
  ServicesTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ServicesTests
      - path: Services
        includes:
          - "**/*_tests.swift"
    dependencies:
      - target: Services